config/routes.rb
Rails.application.routes.draw do
  root to: "todos#index"

  resources :todos, only: [:index, :new, :create] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    Todo.create(todo_params)
    redirect_to todos_path
  end

  private

  def todo_params
    params.require(:todo).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Beth's To Do List</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>To Do!</h1>
    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<%= link_to "Create Todo", new_todo_path %>

<ul class="todos">
  <% @todos.each do |todo| %>
    <li> <%= todo.title %> </li>
  <% end %>
</ul>

app/views/todos/new.html.erb
<h1> Create New To Do Item </h1>

<%= form_for @todo do |form| %>
<%= form.label :title %>
<%= form.text_field :title %>
<%=form.submit "Submit"%>
<%end %>